### ISSUE TITLE
Refactor lightcone

### ISSUE THREAD

**Issue by marcelo-alvarez** [marcelo-alvarez/lptmap#3]
Currently `light_cone.py` (i.e. the "MPI implementation" of light cone projection) has paths and grid parameters hardcoded.  In order to prototype the interface to light cone projection functionality as part of a larger external framework that does not yet exist, it will be desirable to first refactor the operations currently in `light_cone.py` into a concrete class developed within this repository, which would then provide some input into the structure of the more abstract base class from the external framework to support it.

**Comment by 1cosmologist** [comment]
@marcelo-alvarez Do you think the current implementation of `liblightcone` has solved this issue?

**Comment by marcelo-alvarez** [comment]
@1cosmologist closed and moved to https://github.com/exgalsky/lightcone/issues/4.
