### ISSUE TITLE
Profile memory usage and track memory leaks

### ISSUE THREAD

**Issue by 1cosmologist** [marcelo-alvarez/lptmap#5]
We need to profile line-by-line memory usage of the light_cone codes (both MPI and JAX) and ensure that the memory usage matches to calculation. When running the MPI implementation for the full 6144 cube on Perlmutter, there was definite memory leak. We need to check for memory spikes during function calls and ensure the memory management is reasonable for future additions like 2LPT and multiple kernels.

**Comment by marcelo-alvarez** [comment]
@1cosmologist closed and moved to https://github.com/exgalsky/lightcone/issues/3.
