### ISSUE TITLE
Only print status messages from root MPI task

### ISSUE THREAD

**Issue by marcelo-alvarez** [marcelo-alvarez/lptmap#9]
Currently most if not all print messages are executed regardless of the MPI task, which will render the output illegible for large runs. In methods that have access to the `backend` object, `bk`, this can be accomplished with, e.g.,
```
if (bk.mpi_backend.id == 0) print("some status message)
```
However in some other cases, such as in `jax_utils.py`, it would require an as yet unimplemented way of having the current task's ID available in the same scope as the print statement that should only be executed on the root MPI task.

**Comment by 1cosmologist** [comment]
This issue has been addressed in the `log_utils` module. We have custom logging level implemented via python logging module. Currently we can print information from MPI root or all processes depending on requirement. This is now part of the main branch via the PR  #11.
